services:
  myevilchatrobot.api:
    image: ${DOCKER_REGISTRY-}myevilchatrobotapi
    build:
      context: .
      dockerfile: MyEvilChatRobot.API/Dockerfile

  myevilchatrobot.ui:
    image: ${DOCKER_REGISTRY-}myevilchatrobotui
    build:
      context: .
      dockerfile: MyEvilChatRobot.UI/Dockerfile

